# https://pre-commit.com
# https://pre-commit.com/hooks.html

default_language_version:
  python: python3.13
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v5.0.0'
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.11.5'
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        # exclude: tests/
        additional_dependencies:
            - "pandera[mypy]>=0.23.0"
            - "pydantic>=2.10.6"
            - "pydantic-settings>=2.8.1"
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 'v4.4.1'
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [pre-push]
